export const APP_NAME = 'Stravell';
export const HOME_PAGE_TITLE = `${APP_NAME} | Home`;
export const LOG_IN_PAGE_TITLE = `${APP_NAME} | Log In`;
export const DASHBOARD_PAGE_TITLE = `${APP_NAME} | Dashboard`;
export const APP_POST_PAGE_TITLE = `${APP_NAME} | Add Post`;
export const EDIT_POST_PAGE_TITLE = `${APP_NAME} | Edit Post`;
export const NOT_FOUND_PAGE_TITLE = `${APP_NAME} | 404 Not Found`;
export const USER_WALL_PAGE_TITLE = `${APP_NAME}`;
export const MIN_NUM_OF_CHARACTERS_FOR_TITLE = 5;
export const MAX_NUM_OF_CHARACTERS_FOR_TITLE = 80;
export const MIN_NUM_OF_CHARACTERS_FOR_DESCRIPTION = 5;
export const MAX_NUM_OF_CHARACTERS_FOR_DESCRIPTION = 180;
export const MIN_NUM_OF_CHARACTERS_FOR_BODY = 100;
export const SLOGAN = "Let's explore the world together."
